version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: factorypro-mysql
    restart: always
    environment:
      MYSQL_DATABASE: factorypro_db
      MYSQL_USER: factorypro
      MYSQL_PASSWORD: factorypro
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - factorypro-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: factorypro-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - factorypro-network

networks:
  factorypro-network:
    driver: bridge

volumes:
  mysql-data:
