version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: factorypro-mysql
    restart: always
    environment:
      MYSQL_DATABASE: factorypro_db
      MYSQL_USER: factorypro
      MYSQL_PASSWORD: factorypro
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      # - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - factorypro-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: factorypro-phpmyadmin
    restart: always
    environment:
      PMA_HOST: factorypro-mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - factorypro-network

  web:
    build: .
    container_name: factorypro-nextjs
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/factorypro_db
    volumes:
      - ./public:/app/public
    networks:
      - factorypro-network
networks:
  factorypro-network:
    driver: bridge

volumes:
  mysql-data:
